### PR TITLE
Db refactoring

### PR DESCRIPTION
**Pull request by romangraef**
do not merge yet
EDIT: do merge

### CODE REVIEW

**Comment by romangraef** [comment]
Okay, I'm done. hopefully everything is ok for you two.

**Comment by Randium** [comment]
How is this refactoring? You literally replaced every `ìsParticipant` with `is_participant`.

I can use `Ctrl+F => replace` too, ya know. The command wouldn't be called `isParticipant` if it wasn't for a reason.

**Comment by Randium** [comment]
Anyway, I am currently rewriting some parts of the database as well. But this will be more than a simple function rename.

**Comment by romangraef** [comment]
@Randium did you even look at the code? Like literally replacing a function call? Look at the code. look at it. I refactored the whole fucking database file. Also why do you called it isParticipant when python conventions say it should be is_participant. another thing: don't use CTRL+F replace but rather some more advanced refactoring tool like refactor -> rename. There is a difference between an API change and an internal change.

**Comment by Randium** [comment]
I've looked at it, yes. And I've noticed it's literally just throwing it into some auto-changer.

Lemme know when you have some ACTUAL changes that actually change anything about the bot.

**Comment by romangraef** [comment]
You mean ACTUAL changes except for `management/db.py`.. Look at that specific file and say that to me again.

**Comment by romangraef** [comment]
Btw. i said db refactoring. there is one file you dont look at. it is the file with the "large diff" warning. it is the database file. makes sense that there is no important changes in the one file that should be changed, right?

**Comment by lineargraph** [comment]
@Randium?

**Comment by lineargraph** [comment]
@Randium could you stop ignoring your failures?

**Pull request closed without merging**
