### PR TITLE
Move stuff to config

### PR DESCRIPTION
**Pull request by Bentechy66**
Pfft, already not following coding guidelines.

### CODE REVIEW

**Comment by Randium** [comment]
Does it create a config file? All I can see, is that it deletes stuff from main.py, but that it doesn't move it to a new file.

**Comment by Bentechy66** [comment]
See other pull

**Comment by Randium** [comment]
Ah, I see. Excellent.

Though I do think a shortcut for config wouldn't be a problem. Maybe c? c.TOKEN? con.game_master?
Or would config.game_master, though long, suffice?

**Comment by Bentechy66** [comment]
Always keep your variable names understandable. `c` doesn't tell me anything about what that variable actually is.

**Pull request merged**
