### PR TITLE
Merge mailbox system

### PR DESCRIPTION
**Pull request by Randium**
In this system, the administration is done underneath the hood, and whenever a function is done with the administration, it passes a mailbox that contains messages that need to be sent to the game_log, to specific channels, specific DMs etc. When everything has been done, the Mailbox should arrive in main.py, where it should be unpacked, and all messages should be sent to the right locations.

The reason I think we should use Mailboxes rather than just sending them right away, is because some messages must not arrive immediately, but rather arrive at a certain moment; for example, sometimes messages need to appear after a player has been killed at the end of the night, and not immediately when the task has been given to kill the player.

### CODE REVIEW

**Comment by Randium** [comment]
It's got merge conflicts because it cannot find the files lib/participant.py and lib/role.py
I deleted those as soon as I forked the repostory, that's why it doesn't find them, I guess.

**Comment by Randium** [comment]
Also, can I add a few more commits to this pull request, or is that not possible?

**Comment by HurricanKai** [comment]
Yes, until merge, just add more and more Commits on your Fork @Randium

**Comment by Randium** [comment]
I see. It works! Thanks!

Also, does my fork disappear when the pull is accepted, or does it remain a different repository?

**Comment by HurricanKai** [comment]
It remains & the Merge Conflicts will be solved there too, i think. thought im not shure about the Merge Conflicts. *Fix those* (yes, the best way is to download GitHub desktop, if you dont have it, get it, and if you cant, call me maybe, ill may fix it for you)

**Comment by HurricanKai** [comment]
See #6

**Pull request closed without merging**
