### PR TITLE
powder command

### PR DESCRIPTION
**Pull request by romangraef**

### CODE REVIEW

**Comment by Randium** [comment]
Have you tested this? Are you sure all these newlines work?

**Comment by romangraef** [comment]
@Randium yes i did

**Comment by Randium** [comment]
You mean you tested them? How? When? Where?

**Comment by Randium** [comment]
Did a generator change this fo you automatically? Did you change this manually? Are you sure that this works because out of experience of because you did a live test?

**Comment by Bentechy66** [comment]
I see no reason this _shouldn't_ work

**Comment by Randium** [comment]
Aight. Then you can approve it and we can merge it.

**Pull request merged**
