### PR TITLE
Pr/5 Fixed Merge.

### PR DESCRIPTION
**Pull request by HurricanKai**
See Former #5

### CODE REVIEW

**Comment by Randium** [comment]
Not bad. Though we now have two different role systems. I do think we need to discuss what we're gonna do right here.

**Comment by Randium** [comment]
Shall I pull it? I'm happy with it.

**Comment by HurricanKai** [comment]
you cant pull it, its a different branch on this Repo. i guess this first has to be merged, and then you can merge this one with yours again, and then we are equal again
yeah.. something like that

**Comment by Randium** [comment]
No, I mean, I can merge it. Oh well, YOLO. :P 
I guess we can always turn it back.

**Pull request merged**
