### PR TITLE
Add Theret code

### PR DESCRIPTION
**Pull request by Randium**
Yay! It's suddnly become to send and receive code to and from the virtual machine! Thanks, @TheretVM!

### CODE REVIEW

**Comment by TheretVM** [comment]
You're welcome, bro. Also, I love the pull request!
You know what? Let's do it, let's merge this!

**Comment by Randium** [comment]
Yeah, hahah, I bet you can't wait to see your own code being used on the Werewolf Bot!

**Comment by TheretVM** [comment]
Yeah, I'd love to. Nothing seems more epic and awesome to me than being a bt developer, one that actively contributed to the Werewolf Bot!
You know, that kind. Not the kind that's like, _"I wanna contribute to the Werewolf Bot - you know what, let me make a quoting system,"_ no, I wanna be the kind that actively contributes to the actual structure, to the actual things that need to be done to get the Werewolf Bot going! Oh, I have some really cool extra ideas of my own that I would like to contribute - but I'm just so enthusiastic that I'm willing to wait and get the **BIG JOB** done!

**Comment by Randium** [comment]
That is nice to hear, @TheretVM! I think I will reward you with the Game Master role if you keep this going!

**Comment by TheretVM** [comment]
Oh, really? Oh, thank you! I've always wanted to be one!

Oh, this makes me so happy, that I'm gonna contribute **EVEN MORE!** Game Masters, here I come!

**Pull request merged**
